name: kem
description: "Enhanced Security Scanner with Persistent Background Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Core scanning functionality
  mobile_scanner: ^4.0.1
  permission_handler: ^11.4.0
  camera: ^0.10.6
  
  # Location services
  location: ^5.0.3
  geolocator: ^14.0.0
  
  # Device information
  device_info_plus: ^9.1.2
  
  # Networking
  http: ^1.4.0
  socket_io_client: ^3.1.2
  
  # Background services
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  
  # Storage and file handling
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.5.1
  
  # UI notifications
  flutter_local_notifications: ^17.2.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true